global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tic-tac-toe'
    dns_sd_configs:
      - names:
          - 'tasks.tictactoe_tictactoe'
        type: 'A'
        port: 3306
    metrics_path: '/metrics'
